[package]
name = "average-commit-time"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
git2 = "0.13.20"
glob = "0.3.0"
rayon = "1.5.1"
